name: Auto Build Latest Tag

on:
  schedule:
    - cron: '0 19 * * *' # 每天 UTC 19:00，即北京时间 03:00
  workflow_dispatch:

jobs:
  check-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Tag from New API
        id: latest_tag
        run: |
          echo "LATEST_TAG=$(wget -qO- https://api.github.com/repos/Calcium-Ion/new-api/tags | gawk -F '\"' '/name/{print $4;exit}')" >> $GITHUB_ENV

      - name: Get Latest Tag Built in Current Repo
        id: current_tag
        run: |
          echo "CURRENT_TAG=$(wget -qO- https://api.github.com/repos/${{ github.repository }}/releases/latest | gawk -F '\"' '/tag_name/{print $4;exit}')" >> $GITHUB_ENV

      - name: Compare Tags
        if: env.LATEST_TAG != env.CURRENT_TAG
        run: |
          echo "Need to build the tag: ${{ env.LATEST_TAG }}"

      - name: Checkout Code
        if: env.LATEST_TAG != env.CURRENT_TAG
        uses: actions/checkout@v4

      - name: Build Project
        if: env.LATEST_TAG != env.CURRENT_TAG
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y wget curl git gcc bash gawk gsed
            wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz && rm go1.22.0.freebsd-amd64.tar.gz
            ln -s /usr/local/go/bin/go /usr/local/bin/go
          run: |
            cd new-api
            go mod download
            go build -ldflags "-s -w -X 'github.com/Calcium-Ion/new-api/common.Version=${{ env.LATEST_TAG }}' -extldflags '-static'" -o new-api

      - name: Upload artifact
        if: env.LATEST_TAG != env.CURRENT_TAG
        uses: actions/upload-artifact@main
        with:
          name: new-api
          path: |
            new-api

      - name: Create Release
        if: env.LATEST_TAG != env.CURRENT_TAG
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST_TAG }}
          files: |
            new-api