name: FreeBSD Multi-Tag Builder

on:
  workflow_dispatch:
    inputs:
      test_tags:
        description: '测试版本（逗号分隔，留空处理全部未构建版本）'
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      build_list: ${{ steps.prepare-tags.outputs.build_list }}
    steps:
      - name: 获取上游所有tags
        id: get-upstream-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          all_tags=()
          page=1
          while :; do
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/Calcium-Ion/new-api/tags?per_page=100&page=$page")
            tags=$(echo "$response" | jq -r '.[] | [.name, .commit.commit.committer.date] | @tsv' | sort -k2 | cut -f1)

            [ -z "$tags" ] && break
            all_tags+=($tags)
            ((page++))
          done
          echo "sorted_tags=${all_tags[*]}" >> $GITHUB_OUTPUT

      - name: 获取已发布版本
        id: get-released
        run: |
          released_tags=$(gh release list --limit 1000 | awk '{print $1}')
          echo "released_tags=${released_tags[*]}" >> $GITHUB_OUTPUT

      - name: 生成构建列表
        id: prepare-tags
        run: |
          IFS=' ' read -ra sorted_tags <<< "${{ steps.get-upstream-tags.outputs.sorted_tags }}"
          IFS=' ' read -ra released_tags <<< "${{ steps.get-released.outputs.released_tags }}"

          declare -A released_map
          for tag in "${released_tags[@]}"; do
            released_map[$tag]=1
          done

          build_list=()
          for tag in "${sorted_tags[@]}"; do
            [[ -z "${released_map[$tag]}" ]] && build_list+=("$tag")
          done

          if [ -n "${{ github.event.inputs.test_tags }}" ]; then
            IFS=',' read -ra test_tags <<< "${{ github.event.inputs.test_tags }}"
            build_list=("${test_tags[@]}")
          fi

          echo "需要构建的版本数量：${#build_list[@]}"
          echo "build_list=${build_list[*]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.build_list != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: FreeBSD 构建
        uses: vmactions/freebsd-vm@v1
        id: freebsd-build
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg update -y
            pkg install -y git gcc bash gmake go120 node npm rsync
            wget -q https://dl.google.com/go/go1.23.4.freebsd-amd64.tar.gz
            tar -C /usr/local -xzf go1.23.4.freebsd-amd64.tar.gz
            ln -sf /usr/local/go/bin/go /usr/local/bin/go
          run: |
            set -xe
            IFS=' ' read -ra TAGS <<< "${{ needs.prepare.outputs.build_list }}"

            # 定义工作区路径
            WORKSPACE="/github/workspace"
            OUTPUT_DIR="$WORKSPACE/releases"
            mkdir -p "$OUTPUT_DIR"
            chmod 777 "$OUTPUT_DIR"

            for TAG in "${TAGS[@]}"; do
              echo "=== 开始构建 $TAG ==="
              BUILD_DIR=$(mktemp -d)

              # 克隆代码
              git clone -b "$TAG" --depth 1 https://github.com/Calcium-Ion/new-api "$BUILD_DIR"

              # 前端构建
              cd "$BUILD_DIR/web"
              npm ci --prefer-offline --no-audit --no-fund --loglevel=error
              REACT_APP_VERSION="$TAG" npm run build --silent

              # 后端构建
              cd "$BUILD_DIR"
              go mod download
              go build -ldflags "-s -w -X 'one-api/common.Version=$TAG' -extldflags '-static'" -o "$OUTPUT_DIR/new-api-$TAG"

              # 清理
              rm -rf "$BUILD_DIR"
              echo "=== $TAG 构建完成 ==="
            done

            # 验证输出文件
            ls -lh "$OUTPUT_DIR"
            echo "::set-output name=build_success::true"

      - name: 上传制品
        if: steps.freebsd-build.outputs.build_success == 'true'
        uses: actions/upload-artifact@main
        with:
          name: freebsd-binaries
          path: ./releases/new-api-*
          retention-days: 3

      - name: 发布版本
        if: steps.freebsd-build.outputs.build_success == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./releases
          for binary in new-api-*; do
            TAG="${binary#new-api-}"
            echo "发布版本: $TAG"
            gh release create "$TAG" \
              --title "$TAG (FreeBSD)" \
              --notes "Automated build" \
              --prerelease \
              "$binary"
          done

      - name: 清理旧版本
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tags=$(echo "${{ needs.prepare.outputs.build_list }}" | tr ' ' '\n')
          gh release list --limit 100 | awk '/pre-release/{print $1}' | while read tag; do
            if ! echo "$current_tags" | grep -qx "$tag"; then
              echo "删除旧版本: $tag"
              gh release delete -y "$tag" || true
            fi
          done