name: Build All Tags

on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Get All Tags from New API
        id: get_all_tags
        run: |
          TAGS=$(wget -qO- https://api.github.com/repos/Calcium-Ion/new-api/tags | gawk -F '"' '/name/{print $4}')
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Get All Tags Built in Current Repo
        id: get_built_tags
        run: |
          TAGS_BUILT=$(wget -qO- https://api.github.com/repos/${{ github.repository }}/releases | gawk -F '"' '/tag_name/{print $4}')
          echo "TAGS_BUILT=$TAGS_BUILT" >> $GITHUB_ENV

      - name: Build and Release Tags Sequentially
        run: |
          for TAG in $TAGS; do
            if echo "$TAGS_BUILT" | grep -qw "$TAG"; then
              echo "Skipping $TAG (already built)"
            else
              echo "Building $TAG"
              gh workflow run build_tag.yml -f tag_name="$TAG"

              # Poll for the job completion - to ensure sequential build
              while [ $(gh run list --workflow build_tag.yml --json conclusion -q 'length([.[] | select(.conclusion == null)])') -gt 0 ]; do
                echo "Waiting for build to complete..."
                sleep 30
              done
            fi
          done
        env:
          TAGS: ${{ steps.get_all_tags.outputs.TAGS }}
          TAGS_BUILT: ${{ steps.get_built_tags.outputs.TAGS_BUILT }}