name: Build All Versions

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-tags.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: |
          git remote add upstream https://github.com/Calcium-Ion/new-api.git
          git fetch upstream --tags -f

      - name: Get unreleased tags
        id: get-tags
        run: |
          # 获取所有本地标签
          ALL_TAGS=$(git tag -l "v*" --sort=-v:refname)

          # 获取已存在的Release标签
          RELEASED_TAGS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[].tag_name')

          # 生成未构建标签矩阵
          UNBUILT_TAGS=$(comm -23 <(echo "$ALL_TAGS" | sort) <(echo "$RELEASED_TAGS" | sort))
          echo "matrix=$(echo $UNBUILT_TAGS | jq -R -s -c 'split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Build Version
        uses: ./.github/workflows/build-single.yml
        with:
          tag: ${{ matrix.tag }}