name: FreeBSD Multi-Tag Builder

on:
  workflow_dispatch:
    inputs:
      test_tags:
        description: '测试版本（逗号分隔，留空处理全部未构建版本）'
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      build_list: ${{ steps.prepare-tags.outputs.build_list }}
    steps:
      - name: 获取上游所有tags
        id: get-upstream-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取按时间排序的tag列表（旧到新）
          all_tags=()
          page=1
          while :; do
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/Calcium-Ion/new-api/tags?per_page=100&page=$page")
            tags=$(echo "$response" | jq -r '.[] | [.name, .commit.commit.committer.date] | @tsv' | sort -k2 | cut -f1)

            [ -z "$tags" ] && break
            all_tags+=($tags)
            ((page++))
          done
          echo "sorted_tags=${all_tags[*]}" >> $GITHUB_OUTPUT

      - name: 获取已发布版本
        id: get-released
        run: |
          # 使用GitHub CLI获取已发布版本
          released_tags=$(gh release list --limit 1000 | awk '{print $1}')
          echo "released_tags=${released_tags[*]}" >> $GITHUB_OUTPUT

      - name: 生成构建列表
        id: prepare-tags
        run: |
          IFS=' ' read -ra sorted_tags <<< "${{ steps.get-upstream-tags.outputs.sorted_tags }}"
          IFS=' ' read -ra released_tags <<< "${{ steps.get-released.outputs.released_tags }}"

          declare -A released_map
          for tag in "${released_tags[@]}"; do
            released_map[$tag]=1
          done

          build_list=()
          for tag in "${sorted_tags[@]}"; do
            [[ -z "${released_map[$tag]}" ]] && build_list+=("$tag")
          done

          # 测试模式处理
          if [ -n "${{ github.event.inputs.test_tags }}" ]; then
            IFS=',' read -ra test_tags <<< "${{ github.event.inputs.test_tags }}"
            build_list=("${test_tags[@]}")
          fi

          echo "需要构建的版本数量：${#build_list[@]}"
          echo "build_list=${build_list[*]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.build_list != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要删除发布的权限
    strategy:
      max-parallel: 3  # 控制并发数量
    steps:
      - uses: actions/checkout@v4

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 安装GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: 批量构建 (FreeBSD)
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            # 一次性安装所有依赖
            pkg update -y
            pkg install -y git gcc bash gmake go120 node npm
            wget https://dl.google.com/go/go1.23.4.freebsd-amd64.tar.gz
            tar -C /usr/local -xzf go1.23.4.freebsd-amd64.tar.gz
            ln -s /usr/local/go/bin/go /usr/local/bin/go
            mkdir -p /builds
          run: |
            set -e
            IFS=' ' read -ra TAGS <<< "${{ needs.prepare.outputs.build_list }}"

            for TAG in "${TAGS[@]}"; do
              echo "=== 开始构建 $TAG ==="
              BUILD_DIR="/builds/$TAG"

              # 创建独立构建环境
              mkdir -p $BUILD_DIR
              cd $BUILD_DIR

              # 克隆指定版本代码
              git clone -b $TAG --depth 1 https://github.com/Calcium-Ion/new-api src

              # 前端构建（优化缓存策略）
              cd src/web
              echo "安装前端依赖..."
              if [ -f package-lock.json ]; then
                npm ci --prefer-offline --no-audit --no-fund --loglevel=error
              else
                npm install --prefer-offline --no-audit --no-fund --loglevel=error
              fi
              echo "构建前端资源..."
              REACT_APP_VERSION=$TAG npm run build --silent

              # 后端构建（启用缓存）
              cd ..
              echo "下载Go依赖..."
              go mod download
              echo "编译二进制文件..."
              go build -ldflags "-s -w -X 'one-api/common.Version=$TAG' -extldflags '-static'" -o ../new-api-$TAG

              # 清理中间文件（节省空间）
              cd ../..
              rm -rf $BUILD_DIR
              echo "=== $TAG 构建完成 ==="
            done

      - name: 上传制品
        uses: actions/upload-artifact@main
        with:
          name: freebsd-binaries
          path: /builds/new-api-*
          retention-days: 3

      - name: 批量发布版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /builds
          for binary in new-api-*; do
            TAG=${binary#new-api-}
            echo "正在发布版本: $TAG"
            gh release create $TAG \
              --title "$TAG (FreeBSD)" \
              --notes "Automated build for FreeBSD" \
              --prerelease \
              $binary
          done

      - name: 清理旧预发布版本
        if: always()  # 即使前面步骤失败也执行
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "当前构建的版本: ${{ needs.prepare.outputs.build_list }}"
          # 生成排除列表
          CURRENT_TAGS=$(echo "${{ needs.prepare.outputs.build_list }}" | tr ' ' '\n' | sed 's/^/\\</;s/$/\\>/')

          # 清理逻辑
          gh release list --limit 100 | awk '/pre-release/{print $1}' | while read tag; do
            if ! echo "$tag" | grep -qFf <(echo "$CURRENT_TAGS"); then
              echo "正在删除旧版本: $tag"
              gh release delete -y "$tag" || echo "删除失败（可能已不存在）"
            else
              echo "保留当前版本: $tag"
            fi
          done