name: Build Action

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          echo ${{ inputs.tag }} > VERSION
          REACT_APP_VERSION=${{ inputs.tag }} npm run build
          mv build ../web-build
          cd ..

      - name: Prepare FreeBSD Build
        run: |
          mkdir -p artifacts
          cp -r web-build artifacts/

      - name: FreeBSD Backend Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y go gmake
            wget https://golang.org/dl/go1.22.0.freebsd-amd64.tar.gz
            tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz
          run: |
            export PATH=$PATH:/usr/local/go/bin
            cd /home/runner/work/new-api/new-api
            go mod download
            go build -ldflags "-s -w -X 'github.com/Calcium-Ion/new-api/common.Version=${{ inputs.tag }}'" -o new-api
            cp new-api /home/runner/work/new-api/new-api/artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            artifacts/new-api
            artifacts/web-build/*