name: Auto Build Latest

on:
  schedule:
    - cron: '0 19 * * *'  # UTC时间19点（北京时间凌晨3点）
  workflow_dispatch:      # 保留手动触发

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch upstream tags
        run: |
          git remote add upstream https://github.com/songquanpeng/one-api.git
          git fetch upstream --tags -f

      - name: Get latest tag
        id: get-latest
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Check existing release
        id: check-release
        run: |
          EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get-latest.outputs.tag }}")
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

      - name: Build Backend Only
        if: steps.check-release.outputs.exists != '200'
        uses: ./.github/workflows/build-single.yml
        with:
          tag: ${{ steps.get-latest.outputs.tag }}