name: Auto Sync and Build

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3 点自动检查

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/songquanpeng/one-api.git
          git fetch upstream --tags

      - name: Sync new tags
        run: |
          # 获取所有未同步的标签
          existing_tags=$(git tag -l)
          upstream_tags=$(git ls-remote --tags upstream | awk -F/ '{print $3}')
          new_tags=$(comm -23 <(echo "$upstream_tags" | sort) <(echo "$existing_tags" | sort))

          # 推送新标签到当前仓库
          for tag in $new_tags; do
            git tag $tag
            git push origin $tag
          done

  build-new-versions:
    needs: sync-tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get-tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Release
        uses: ./.github/workflows/build-action.yml
        with:
          tag: ${{ steps.get-tag.outputs.tag }}