name: Batch Build Tags

on:
  workflow_dispatch:
    inputs:
      test-mode:
        description: 'Test mode (build first N tags)'
        required: false
        default: '0'
        type: string

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    outputs:
      tag_list: ${{ steps.get-tags.outputs.tag_list }}
    steps:
      - name: Get all upstream tags
        uses: actions/github-script@v7
        id: get-tags
        with:
          script: |
            try {
              // 获取上游所有tags
              const upstreamTags = await github.paginate(
                github.rest.repos.listTags,
                {
                  owner: 'Calcium-Ion',
                  repo: 'new-api',
                  per_page: 100
                }
              )

              console.log('upstreamTags===', upstreamTags)

              // 获取当前所有release（处理空release情况）
              let currentReleases = []
              try {
                currentReleases = await github.paginate(
                  github.rest.repos.listReleases,
                  {
                    owner: context.repo.owner,
                    repo: context.repo.repo
                  }
                )
              } catch (error) {
                console.log('No existing releases found')
              }

              // 处理可能的空数据情况
              const existingTags = new Set((currentReleases || []).map(r => r.tag_name))
              let newTags = upstreamTags
                .filter(t => t && t.name && !existingTags.has(t.name))
                .reverse()

              // 测试模式处理
              const testCount = Math.max(0, parseInt('${{ inputs.test-mode }}') || 0)
              if (testCount > 0) {
                newTags = newTags.slice(0, testCount)
              }

              core.setOutput('tag_list', JSON.stringify(newTags))

            } catch (error) {
              core.setFailed(`Failed to get tags: ${error.message}`)
              core.setOutput('tag_list', '[]')
            }

  build:
    needs: fetch-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.fetch-tags.outputs.tag_list) }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare workspace
        run: |
          mkdir -p builds/${{ matrix.tag }}
          cd builds/${{ matrix.tag }}
          git clone -b ${{ matrix.tag }} --depth 1 https://github.com/Calcium-Ion/new-api

      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd builds/${{ matrix.tag }}/new-api/web
          npm install --prefer-offline --no-audit
          REACT_APP_VERSION=${{ matrix.tag }} npm run build
          cd ../../../..

      - name: Build Backend (FreeBSD)
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            if [ ! -f /usr/local/bin/go ]; then
              pkg install -y jq wget curl git gcc bash gawk gsed
              wget -q https://dl.google.com/go/go1.23.4.freebsd-amd64.tar.gz
              tar -C /usr/local -xzf go1.23.4.freebsd-amd64.tar.gz
              rm go1.23.4.freebsd-amd64.tar.gz
              ln -s /usr/local/go/bin/go /usr/local/bin/go
            fi
          run: |
            cd builds/${{ matrix.tag }}/new-api
            go mod download
            go build -ldflags "-s -w -X 'one-api/common.Version=${{ matrix.tag }}' -extldflags '-static'" -o new-api

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: new-api-${{ matrix.tag }}
          path: builds/${{ matrix.tag }}/new-api/new-api

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.tag }}
          prerelease: ${{ inputs.test-mode != '0' }}
          files: builds/${{ matrix.tag }}/new-api/new-api
